name: Build SADEE-DIMA APKs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Flutter project
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "pubspec.yaml:"
          test -f pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze --no-fatal-infos

      - name: Build User APK
        run: flutter build apk --release -t lib/main_user.dart

      - name: Rename User APK
        run: |
          mkdir -p release
          cp build/app/outputs/flutter-apk/app-release.apk \
             release/SADEE-DIMA-USER.apk

      - name: Build Admin APK
        run: flutter build apk --release -t lib/main_admin.dart

      - name: Rename Admin APK
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk \
             release/SADEE-DIMA-ADMIN.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: SADEE-DIMA-APKs
          path: release/
          if-no-files-found: error
